pre-commit/pre-commit.com

all-repos.yaml

In landscapeio/prospector#78, Prospector was updated to allow multiple command line file inputs, which makes it easy to create a pre-commit hook for Prospector. The hook is configured to run as a system hook rather than a python hook to allow pylint to validate imports.
https://github.com/guykisel/prospector-mirror

Add prospector-mirror

---

all-repos.yaml

https://github.com/chriskuehl/puppet-pre-commit-hooks
3 hooks:
* puppet-validate: uses `puppet parser validate` to validate manifests
* erb-validate: compiles erb templates and checks them with `ruby -c`
* puppet-lint
The last obviously overlaps with the puppet-lint mirror, but it seems reasonable to keep these three in one repo.

Add chriskuehl/puppet-pre-commit-hooks

---

all-repos.yaml

I'm moving this [linked repo](https://github.com/SamWhited/go-pre-commit) to [BitBucket](https://bitbucket.org/SamWhited/go-pre-commit). I will remove the GitHub version shortly.

Change Go hooks to new BitBucket URL

---

all-repos.yaml

I looked at the SamWhited/go-pre-commit.git hooks, but they don't quite work for larger repos (`go vet` fails if you pass it files from multiple packages, the `go fmt` hook hides all output) so I created these.

Adding golang hooks

---

index.mako

When I originally wrote this documentation, it was late at night (classic excuse) and I included quotes for the YAML array items. The documentation is corrected here.

Corrected documentation: YAML array items do not need quotes

---

all-repos.yaml

The previous JSCS mirror is out of date and it's pulse it dead.
See https://github.com/hyperNURb/mirrors-jscs/pull/1

Update JSCS hook

---

all-repos.yaml

Currently, [`lintr`](https://github.com/jimhester/lintr) is supported. The hook has been tested (against tag `0.1.0`) with success on an R package in development.

Add repo with pre-commit hooks for R

---

all-repos.yaml

pre-commit hook for reordering ES6 import statements
Verified as working locally, working on adding tests.

added magicmark/pre-commit-es6-imports-reorder

---

.pre-commit-config.yaml
index.mako

Here's documentation for docker bits. Sort of a mouthful, happy to hear better-doc-suggestions
also that ruby version didnt work locally :(

Add dockermentation

---

all-repos.yaml

Seems that github.com/FalconSocial/pre-commit-mirrors-pep257 hasn't been updated in a year and for `pydocstyle` so this repo exists.

Add pydocstyle hook

---

.travis.yml
Makefile
index.mako
install-local.py
make_all_hooks.py
push_to_gh.sh
requirements-dev.txt

- Use python3.6
- Upgrade virtualenv in non-administrative install
- Implement uninstall in non-administrative install
- Implement upgrade in non-administrative install
- Mention how to uninstall / upgrade non-administrative install
Resolves pre-commit/pre-commit#512
- Update make_all_hooks.py for pre-commit 0.13.6
- Simplify push_to_gh.sh
Didn't really mean for this to be a megabranch / megacommit -- one thing led to another and I got carried away :)

Some updates:

---

index.mako

This PR updates documentation according to the changes in the corresponding [PR 538 in pre-commit/pre-commit](https://github.com/pre-commit/pre-commit/pull/538).
I took the liberty to exclude the "An executable must satisfy the following things:" phrase and the list formatting since now there is only one requirement for the hook. I've also assumed the version incorporating this change will be 0.14.0, but in case I'm wrong, then the table must be updated.

Add pass_filenames hook option

---

Makefile

bootstrap.min.js is 404ing, [this article](https://www.bennadel.com/blog/3181-including-node-modules-and-vendors-folders-in-your-github-pages-site.htm) implies I should add a .nojekyll file (might as well try it, why not).

Disable jekyll to get js back

---

.pre-commit-config.yaml
all-repos.yaml
make_all_hooks.py
make_templates.py

In 0.16.0, pre-commit has stopped reading the legacy `hooks.yaml` file and is
instead reading only `.pre-commit-hooks.yaml`.
The following issues track getting this updated / fixed:
- https://github.com/guykisel/pre-commit-robotframework-tidy/issues/1
- https://github.com/hootsuite/pre-commit-php/issues/16
- https://github.com/pricematch/mirrors-closure-linter/issues/1
- https://github.com/elidupuis/mirrors-standard/issues/2
- https://github.com/jordant/rubocop-pre-commit-hook/issues/4
- https://github.com/sanmai-NL/pre-commit-hooks_R/issues/1
- https://github.com/magicmark/pre-commit-es6-imports-reorder/issues/1

Disable hooks which do not provide .pre-commit-hooks.yaml

---

all-repos.yaml

Hi,
We've received a PR on one of those mirrors https://github.com/pricematch/mirrors-rubocop/pull/3, we're actually not maintaining them anymore, and they've become pretty obsolete with support for local hooks in other languages.

Remove pricematch mirrors and hooks

---

index.mako

I mentioned that it is in 1.5.3 but maybe you want to make it more clear that it's not released yet

Updated doc for hook's verbose attribute + fix typo in stages' doc

---

index.mako

Just realized that it was possible to override the name of a hook. I think it's an interesting feature, so I thought I'd document it.

Document the fact that the hook's name can be overriden

---

index.mako

Fixes a link that was pointed at an anchor that didn't exist.

Fix `local` anchor link

---

all-repos.yaml

Mirrors are probably no longer necessary since it's not guaranteed that they will stay up to date.
This was the case especially with `pydocstyle`

Swap mirrors for official PyCQA repos

---

all-repos.yaml

Caters for verifying that pip-compile-multi has been run after changing (multiple) requirements.in files
[pip-compile-multi](https://github.com/peterdemin/pip-compile-multi) allows to benefit from [pip-tools'](https://github.com/jazzband/pip-tools) dependency locking for requirements files combined with the possibility to break them down (eg. `base`, `dev`, `prod`, `test`)

Added pip-compile-multi

---

all-repos.yaml

This repo includes special validation for a few file types commonly used by Mac-centric IT professionals.

Add pre-commit-macadmin

---

all-repos.yaml

This adds a hook that runs [Luacheck](https://luacheck.readthedocs.io/en/stable/) on Lua files.

Add pre-commit-luacheck hook

---

index.mako

Update documentation to cover additional stage: prepare-commit-msg
(_new in X_ to be replaced with version number)
Accompanies https://github.com/pre-commit/pre-commit/pull/1004

Document prepare-commit-msg hooks

---

all-repos.yaml

Both myself and @dnephin had implementations of golangci-lint - However, they've had an official one for [some time now](https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml) - I've sunset mine in my most recent version, and added this so that we can prevent duplication and work and try to get people to use & support the one from the project.

Add the official hook from the golangci-lint project

---

all-repos.yaml

pre-commit-cpp provides two hooks:
* cpplint: style-error detector for Google C++ Style Guide
* cppcheck: static analyzer of C/C++ code

Added pre-commit-cpp to all-repos.yaml

---

all-repos.yaml

This MR adds [cmake-format-pre-commit-hook](https://github.com/iconmaster5326/cmake-format-pre-commit-hook) to the list of all hooks.
It is a hook to run [cmake-format](https://pypi.org/project/cmake-format/) on CMake files.
EDIT: I understand that there is a MR in the works in cmake-format itself to add this support. I heavily doubt that this MR will ever be merged, however, so I recommend accepting this MR over #235. It seems the owner of cmake-format isn't too keen on adding this hook, which is a shame.

Add cmake-format to list of all hooks

---

all-repos.yaml

lisp-format is a tool for autoformatting of Common Lisp code. I helped make the hook for that repo, so I thought I'd update the website here.

Add pre-commit hook for lisp-format

---

all-repos.yaml

We also have `check-gitlab-ci` in https://gitlab.com/smop/pre-commit-hooks, it's have external dependencies - `jq, curl`. 
New version `gitlab-ci-linter` is a pure-python script without external dependencies

Add gitlab-ci-linter

---

index.mako

The `<h1>` tags are not generated with Markdown, while all other sub-headings are generated using Markdown.  Sub-headings render with a nice link, that make it easy for others to reference these sections (highlighted by red box in the example that follows):
---
---
This PR causes `<h1>` headings to render the same as other sub-headings, creating links for subsections.  The following screenshot shows the same section rendered with the changes (green box):
---
---

Update H1 tag formatting to match other headings

---

.pre-commit-config.yaml

mypy 0.660 does not support python 3.8 so the hook was failing to install.
This PR does `pre-commit autoupdate && pre-commit run --all` (all checks passed with the new hook versions).

Autoupdate pre-commit hooks

---

index.mako

The existing docs are not (perfectly) clear about whether `false` will ensure that filenames are _not_ passed in.

Reword pass_filenames docs

---

all-repos.yaml

Refs https://github.com/PyCQA/pylint/pull/3007

Link to upstream pylint repo instead of the pre-commit mirror

---

all-repos.yaml

My hook was registered already and I just changed the source repo of the hook.
Please merge.
Thanks a lot.

Updated link from daverona-env/pre-commit-cpp to toscana/pre-commit-cpp

---

all-repos.yaml

Created a custom pre-commit hook that allows users to perform common gradle tasks on their java projects. Includes a hook (`gradle-other`) that allows execution of any task using arguments.

Add custom gradle hooks repository

---

all-repos.yaml

Sorry to keep bothering you, but the gitlab link for pre-commit-cpp is changed. 
Please merge this fork.
Thank you. :-)

Updated link from toscana/pre-commit-cpp to daverona/pre-commit-cpp

---

index.mako
scss/main.scss

Please preview the mako and see if it looks good. Not sure how to do this on my end on the fly. In GH Markdown you can have indented code blocks in (numbered) lists:
- First
```sh
cat ~/test.txt
```
- Second
```sh
cat ~/test.txt
```
- Unindented
```sh
cat ~/test.txt
```

Add pre-commit badge to docs

---

all-repos.yaml

This adds a kustomize pre-commit hook that can be used to validate that [kustomize](https://github.com/kubernetes-sigs/kustomize) overlays are not broken by the changes.
Please let me know if I am missing something.

kustomize pre-commit hook

---

all-repos.yaml

This is a system for enforcing policies in a repository, including (among other things) the [Conventional Commit standard](https://www.conventionalcommits.org/en/v1.0.0/).

Add Talos's Conform policy enforcement hook

---

index.mako

Since `--commit-msg-filename` is required when using prepare-commit-msg and commit-msg for things like `try-repo`, just making a note of that in the docs.

add note about required arg for {prepare-}commit-msg

---

all-repos.yaml

These are based on a number of existing hook. and they weren't cross platform, these ones all are. Python>bash.

Links to 3 new commit hooks

---

all-repos.yaml

I renamed my pre-commit hook repo to give the repo the same name as the [R package](https://github.com/lorenzwalthert/precommit) (dashes not permitted). I promise to adhere to the spelling *pre-commit* whenever possible and I use *precommit* otherwise :smile:.

Renamed repo

---

index.mako

While setting up a project I realized that there was a typo!

Fix typo on 'pre-commit install-hooks' section

---

all-repos.yaml

This reverts commit 81fa5ad355aff71a5426ca5ffc06598b1549f0bc.
Detect-secrets commit https://github.com/Yelp/detect-secrets/commit/00b9bf8dd035fd8046bb41be1efc907c13646fd5 broke things, and is now fixed.

Revert "Fix broken build" due to detect-secrets

---

all-repos.yaml

This is a modified version of doublify/pre-commit-rust which replaces `rustfmt` by `cargo fmt`, the new standard tool for formatting. 
I opened a PR to them [here](https://github.com/doublify/pre-commit-rust/pull/6) but there doesn't seem to be any interest in merging it so I figured I'd add my hooks here.

Add mathieu-lemay/pre-commit-rust

---

index.mako
template_lib.py

Add special handling for anchors that match the format: `[foo](_#bar)` that adds a named anchor before a self-link
Replace documentation references to configuration keys with links to key documentation where possible
This is the result of some yak-shaving when trying to write some documentation as per https://github.com/pre-commit/pre-commit-hooks/issues/500#issuecomment-646272468
I was hoping to be able to link directly to the relevant configuration key but couldn't do so. Appreciate this is non-standard markdown, so am very open to a better approach, but hopefully this would be a useful addition when pointing users at the docs

Add support for named anchors for all configuration keys for direct linking

---

all-repos.yaml

Removed deprecated "mirrors-isort" repository from all-repos.yaml.

---

index.mako

Updates docs about managing CI caches to include general guidance on how to version the cache, and a specific example of how to do this in CircleCI.

Adds a caching example for CircleCI

---

all-repos.yaml

I created one pre-commit hook for [swiftformat](https://github.com/nicklockwood/SwiftFormat). This PR is to add the repo to the site for other swift devs to find.

docs: add swiftformat hook

---

index.mako

(follow up from Discord).
Files have to be tracked for pre-commit to notice them; uncommitted untracked files are still ignored.

Update wording for uncommitted files in try-repo

---

index.mako

Just noticed this :)
I guess that's what I get for forgetting to submit a pull request to add the example...

Fix circleci example attribution

---

all-repos.yaml

Assuming I have understood how hooks are defined and added to the https://pre-commit.com/hooks.html list, two of the PyCQA repositories were missing.

Add doc8 and prospector

---

all-repos.yaml

This PR:
- ~~Sorts all hooks alphabetically to help improve browsability on https://pre-commit.com/hooks.html. The only exception to this rule is that all of the pre-commit organisation's hooks are listed first.~~
- Adds a new hook https://github.com/radix-ai/auto-smart-commit that automatically formats commit messages as [Jira smart commits](https://confluence.atlassian.com/fisheye/using-smart-commits-960155400.html).

Add radix-ai/auto-smart-commit

---

all-repos.yaml

https://github.com/hukkinj1/mdformat has moved to https://github.com/executablebooks/mdformat
This PR updates the URI

Update mdformat repository owner

---

index.mako

Fixes #283 by adding the description for `stages` from adding plugins to creating hooks.

Document `stages` for new hooks

---

all-repos.yaml

Adds the official cmake-format-precommit hook to the list of repos.
Should the other cmake-format hook be removed from the all_repos.yaml hooks? It's more or less the same but is not the official one. I elected to leave it for now.

Adds cmake-format-precommit to list of all_repos

---

index.mako

Verbose regular expressions allow comments, but if we use "folded"
multiline strings, then the comment will also comment out the
remainder of the regular expression.

Use the "literal" block style instead of the "folded" one

---

all-repos.yaml

I've added a hook for finding and removing unused import statements from Python file(s).

Add pycln to the list of hook repos.

---

all-repos.yaml

Currently contains one hook to run the Detekt static analyzer on Kotlin source files.

add new repo for JVM hooks

---

all-repos.yaml

I didn't see any existing pre-commit hooks for Elixir, so I'm adding these. I currently have hooks for `mix format` and `mix test`, with more planned in the future.

Add elixir-pre-commit-hooks to all_repos.yaml

---

all-repos.yaml

[editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) is a tool to verify that your files are in harmony with your [.editorconfig](https://editorconfig.org/).
The repo adds this via the Python wrapper project: https://github.com/editorconfig-checker/editorconfig-checker.python
This is the second attempt after #415 got rejected. Upstream now provides a `.pre-commit-hooks.yaml`.

Add editorconfig-checker hooks repo

---

index.mako

added example which uses windows environment variables instead of the ~
(see https://github.com/pre-commit/pre-commit/issues/1720#issuecomment-735304274)

added init-templatedir example windows cmd/ps

---

all-repos.yaml

This commit adds a hook that runs [LuaFormatter](https://github.com/LuaDevelopmentTools/luaformatter) on Lua files.

Add pre-commit-lua-formatter hook

---

assets/filter_repos.js
hooks.mako
make_templates.py

resolves #341 
- options for select are automatically generated and only include types for hooks that are in `all-hooks.json`
- also added a search input for the hook id
- repos with non-matching hooks are completely hidden

added id and type filter for hooks

---

all-repos.yaml

Blocklint is a python-based linter for checking any text or source code file for the usage of blocklisted words such as master/slave.  The list of words and sensitivity to case and word boundaries can be configured but the defaults are meant to promote inclusive language in source code.

Add blocklint to list of hook repositories

---

all-repos.yaml

I didn't see another hook which fulfilled this niche, so I've written one which takes care of applying jsonschema validation to JSON or YAML files.
I welcome feedback on the hook itself, if it needs to pass some standard of quality before it can be added. (e.g. I didn't write any tests for it yet.)

Add check-jsonschema to all-repos.yaml

---

all-repos.yaml

* We recently added official pre-commit hook support to jupytext, a program which updates Python notebooks to/from text file representations.
Look forward to seeing this included in the official list of hooks @asottile 😁

Add jupytext to list of hooks

---

all-repos.yaml

The **pre-commit-maven** goal is running [spotless](https://github.com/diffplug/spotless) (and other plugins) in maven-based projects.

Add pre-commit-maven to the list of hook repositories

---

all-repos.yaml

Added tflint pre-commit from the creators of tflint. Uses golang to install, which is different than the ones currently in the list which expect the binary.

added tflint pre-commit from source.

---

all-repos.yaml

Added TFSec pre-commit from TFSec repo. Different than the current tfsec hooks as this builds the package directly from go instead of expecting it to be pre-built on the system.

Add tfsec from source

---

all-repos.yaml

There was already an existing hook listed for hadolint, but the official hadolint repository has now added their own pre-commit hooks.
https://github.com/hadolint/hadolint/pull/523
https://github.com/hadolint/hadolint/pull/527

Add official hadolint repository hook

---

all-repos.yaml

Hello.
Is it possible to add new flutter dependency validation pre-commit hook to be shown then here - https://pre-commit.com/hooks.html?
Hook and some documentation is available here https://github.com/guid-empty/flutter-dependency-validation-pre-commit.
Thank you.

Add new pre-commit hook for Flutter 

---

all-repos.yaml

A pre-commit hook was added to `cpplint` via this [pull-request](https://github.com/cpplint/cpplint/pull/168)
Here I want to update the list of supported hooks on `pre-commit.com`.
The latest cpplint version hasn't been release yet

Add cpplint to the List of Supported Hooks

---

sections/new-hooks.md

This extends the docs for R in the spirit of the other hooks. Note that 
> If the repository is an R package (i.e. has `Type: Package` in `DESCRIPTION`), it is installed.
Is technically true (but useless) in the current release, as discussed in https://github.com/pre-commit/pre-commit/pull/1831. I can also remove this sentence and we add it later.

More details on R hooks

---

all-repos.yaml

CMake-lint is a linter for CMakeFiles. Support for pre-commit was added in commit:
https://github.com/cmake-lint/cmake-lint/commit/f214fecd42cef2aa623742dc9888725bc99d32ba

Add cmake-lint to supported tools.

---

sections/new-hooks.md

Following discussion on stream, updated the wording just to match that
of `files`.

Update wording of 'exclude' hook config setting

---

all-repos.yaml

This hook runs on png files, using oxipng to optimize pngs in a predictable manner.
Requires rust.

Add optimize-png-hooks to list

---

sections/plugins.md

PR #376 included this clarification to the log_file parameter but was rejected because it included other unnecessary formatting changes.

 log_file description

---

all-repos.yaml

Here are two hooks to check the used licenses in a project against a dedicated allow list.

add pre-commit-license-checks to the list of available hooks

---

assets/filter_repos.js

I just checked, which `tex` hooks are available on the website. It seems that filtering on `tex` also shows all the results for `text`. The list is almost identical between the two types.
If I understand the code correctly `hookTypes` is something like `shell, non-executable`. By splitting it on `', '` the `includes` check will work element wise instead of performing a substring match.

Make filtering by hook type use element wise check instead of substring match

---

assets/filter_repos.js

If `type` equals the empty string, no type filter should be applied.
Closes #520

Fix broken search after #512

---

all-repos.yaml

I'm not a Snakemake or snakefmt author, but saw that they have a setup at https://github.com/snakemake/snakefmt/blob/master/.pre-commit-hooks.yaml and it wasn't in the list.

Add snakefmt for Snakemake files

---

all-repos.yaml

I removed `verbose` as per your [comment](https://github.com/twu/skjold/pull/48#discussion_r655524560) with [v0.3.2](https://github.com/twu/skjold/releases/tag/v0.3.2). Apologies for (unintentionally) breaking things. 🙇 
**Proposed Changes**:
- Re-enable `twu/skjold` in `all-hooks.yaml`.

Re-enable skjold.

---

all-repos.yaml

Pyroma 3.2 now supports pre-commit.

Add Pyroma 3.2

---

all-repos.yaml

Code formatter for cell delimiters in interactive iPython notebooks (`# %%`).

all-repos.yaml add format-ipy-cells hook

---

all-repos.yaml

https://github.com/rapidsai/frigate#pre-commit-hook
Frigate is a very nifty tool << for automatically generating documentation for your Helm charts.>>

Prepare frigate integration

---

all-repos.yaml

I've created a hook for Jekyll websites that checks whether absolute links `[absolute link](/absolute/paths)` are used, rather than `[absolute link]({{site.baseurl}}/relative/path)` or similar constructs. More information is in the readme.

Add jekyll-relative-url-hook

---

all-repos.yaml

I ran into some annoying cases of ligature-ized text at work. e.g.
```diff
-conﬁgure
+configure
```
(Gross, eh?)
So I packaged up a fixer as a pre-commit hook! 😄

Add sirosen/fix-ligatures to all-repos

---

.gitattributes

This should prevent conflicts from parallel PR’s like in #580. We’ve done this for [Django’s release notes](https://github.com/django/django/blob/12fe3224f5086161462faf614cad91f3fad32e78/.gitattributes#L7) for a while.

Set Git merge=union for all-repos.yaml

---

all-repos.yaml

I have a couple of hooks which I just consolidated into a single project. This removes my old ones and adds the replacement.
`texthooks` includes a hook which relates to https://github.com/pre-commit/pre-commit-hooks/issues/683, `forbid-bidi-controls`. I disagree about the utility of this hook, but respect the decision not to include it in that repo. Pursuing it on my own seemed best.

Add `texthooks` project, remove hooks it replaces

---

all-repos.yaml

The major difference of this compared to other shfmt hooks listed here is that this one actually installs shfmt (or uses a Docker
image, user's choice), whereas others currently here require it to be installed separately.

Add scop/pre-commit-shfmt

---

all-repos.yaml

Anticipating question "Why `require_serial: true`?" here's rationale: gersemi already spawns additional processes to do the formatting faster in case of multiple files.

Add gersemi CMake formatter

---

all-repos.yaml

This is just like `check-json` from the official hooks, but it tries to load a file with [`json5`](https://pypi.org/project/json5/) instead of the builtin [`json`](https://docs.python.org/3/library/json.html). The [JSON5 spec](https://json5.org/) allows for comments, trailing commas, and more.

Add check-json5 to all-repos.yaml

---

sections/new-hooks.md

Remove the unnecessary `'` symbol

Fix typo in new-hooks.md

---

sections/install.md

Black used to have a problem with [assignment expression](https://github.com/psf/black/pull/1655). Now the docs provide a black version that won't break.

Black version updated

---

hooks.mako

As discussed: https://github.com/pre-commit/pre-commit-mirror-maker/pull/115#pullrequestreview-837778277

Avoid displaying empty descriptions for hooks

---

all-repos.yaml

The upstream repo merged a `.pre-commit-hooks.yaml` file, so the mirror is no longer required. Noted in mirror docs: https://github.com/adamchainz/pre-commit-oxipng#deprecated-2022-01-15

Swap oxipng mirror for source repository

---

all-repos.yaml
sections/new-hooks.md

This branch adds a bit of documentation about the recently merged Lua support. I also added the hook repo for luacheck since that PR was merged with https://github.com/lunarmodules/luacheck/pull/48.
I would like to add the LuaFormatter to this PR, but that PR (https://github.com/Koihik/LuaFormatter/pull/236) has not been merged yet. Since the next version of pre-commit is not out yet, there may be time to slip that in before the next version of pre-commit is released.

Add documentation about Lua language support.

---

all-repos.yaml

The hook using official Lua language support from 2.17.0 for LuaFormatter was merged upstream with https://github.com/Koihik/LuaFormatter/pull/236.
I'd like to add this to the list so that users have this as a visible option over the other hook that depends on the `system` mode.

Add the LuaFormatter hook definition from the canonical repo.

---

scss/_variables.scss
scss/main_bs5.scss

I went to the pre-commit docs to try to find the details of the `fail` language and noticed that searching the page uses a smooth scroll animation which is pretty slow and a bit nausea-inducing:
https://user-images.githubusercontent.com/665269/151456067-3caad462-691d-4c4a-87c8-d44ba207ddc7.mov
I found a fix here which keeps the smooth scrolling when navigating between sections but not when using Ctrl-F to search: https://schepp.dev/posts/smooth-scrolling-and-page-search/
The CSS is a little bit complex, I'm happy to delete this PR if you don't care enough (or just turn off all smooth scrolling if you prefer).

Disable smooth scrolling

---

all-repos.yaml

This rename is one of the reasons for my interest in https://github.com/pre-commit/pre-commit-hooks/issues/726 . It would be nice to somehow get this update into consuming repos.
The plan is to move the `jsonschema` lib into `python-jsonschema` and make this the pre-commit hook for any `jsonschema` usage.
... Anywho, this is just a rename! 😄

Update the home of 'check-jsonschema'

---

all-repos.yaml

Add a reference to the Sceptre pre-commit linter.  This linter checks
sceptre stack configurations[1]
[1] https://docs.sceptre-project.org/dev/docs/stack_config.html

A linter for Sceptre stack configs

---

sections/advanced.md

Document issue with gitlab non-constant build location that clashes with pre-commit's cache that expects a constant location.
This relates to https://github.com/pre-commit/pre-commit/issues/1133#issuecomment-985053269

Document issue with gitlab non-constant build location

---

all-repos.yaml

Thanks for the `pre-commit` tool.
This pull request adds `https://github.com/cmhughes/latexindent.pl` to the all-repos.yaml file. I hope this is the appropriate place, let me know if not.

added latexindent.pl to all-repos.yaml

---

all-repos.yaml

I'd like to add ripsecrets to your list of repos supporting pre-commit. It helps prevent developers from accidentally checking secrets into their source code. Thanks!

Add ripsecrets to all-repos.yaml

---

sections/new-hooks.md

Explicitly declare that `verbose` is `false` by default in "Creating new hooks" section.

Explicit `verbose == false` by default defining hooks

---

all-repos.yaml

cc @redwarp -- seems this was intentional deprecation 👍

remove redwarp/optimize-png-hooks which sets `verbose: true`

---

all-repos.yaml

`terraform_validate` hook doesn't work. I've opened the ticket with the problem description but it seems authot decided to archive the repository. So, I think it is better to remove it from the "pre-commit hooks" page.
**Reference**
https://github.com/kintoandar/pre-commit/issues/9

Remove `kintoandar/pre-commit`

---

all-repos.yaml

Something I've been working on https://github.com/MarcoGorelli/cython-lint, looks like it'd only be the second hook here (after isort) to run on cython files

Add cython-lint to list of hooks

---

sections/advanced.md

With a bit of delay: This PR removes the logoColor option for the shields.io badges. 
The double-escaping comes from `template_lib`, feel free to pull in https://github.com/pre-commit/pre-commit.com/compare/main...mhils:pre-commit.com:no-double-escape instead/as well if that makes sense for you.

badge: remove logoColor

---

sections/cli.md

Changed the link to `default_install_hook_types` in the `pre-commit install` section of the docs to point from `#top_level-default_language_version` to `#top_level-default_install_hook_types`.
Fixes #746

Fix link to `default_install_hook_types` in `cli` section

---

all-repos.yaml

adds pre-commit hooks to
- add a Pre-Commit-Config: trailer to commit messages on `commit-msg`
- add ssh based git signing key to ssh agent on `commit-msg`
- remove ssh based git signing key from ssh-agent on `post-commit`
Implemented as POSIX shell scripts for portability and simplicity.
In https://github.com/pre-commit/pre-commit.com/pull/684#issuecomment-1184377808 you state
> - `language: script` hooks miss the point of the framework as they require users to install tools outside of the framework to use them and as such I'm not allowing new ones onto the hooks page
I have raised this merge request for visibility and considerations of the `add-pre-commit-config-trailer` hook, which was mentioned in https://github.com/pre-commit/pre-commit/issues/582#issuecomment-1316032165 as a …

add pre-commit-trailer and pre-commit-ssh-git-signing-key

---

all-repos.yaml

checkmake got a hook configuration in https://github.com/mrtazz/checkmake/commit/4e37f3a6ea00208b3f5bd04eaa0f075068237f18

Adds checkmake repo

---

sections/install.md

As mentioned in https://github.com/pre-commit/pre-commit/issues/2663 :
> Newcomers tend to copy-and-paste from documentation to try things out, if they get an error they'll tend to assume that something went wrong with their installation
>
> I understand not wanting to always keep it pinned to the latest versions, but at least not pinning to a broken rev seems like a reasonable ask

Use non-broken rev in black formatter hook

---

sections/advanced.md

Noticed some environment variables were missing from the `post-merge`
and `pre-push` hooks in the documentation while developing some new hooks, so added them to the corresponding section.
Specifically added:
-  `PRE_COMMIT_IS_SQUASH_MERGE`
- `PRE_COMMIT_LOCAL_BRANCH`
- `PRE_COMMIT_REMOTE_BRANCH`
_The introduction of `PRE_COMMIT_REMOTE_BRANCH` environment variable can be found in the [Changelog here](https://github.com/pre-commit/pre-commit/blob/main/CHANGELOG.md#2100---2021-01-27).
The introduction of `PRE_COMMIT_LOCAL_BRANCH` environment variable can be found in the [Changelog here](https://github.com/pre-commit/pre-commit/blob/main/CHANGELOG.md#2140---2021-08-06)._

Add missing env variables from docs

---

all-repos.yaml

Add clang-format docs to all-repos

---

all-repos.yaml

Add rubocop/rubocop to all-repos.yaml

---

sections/new-hooks.md

Some edits to the rust section to make it clear that Rust is not required on your system since https://github.com/pre-commit/pre-commit/pull/2534 . I copied from the recent golang edit: https://github.com/pre-commit/pre-commit.com/pull/779/files#diff-eb3204ca6c95d85efdd8fad58315793d3e9e7099edec604b8b659677e87d26b5R320-R321

Better document Rust's first-class support

---

all-repos.yaml

Removing this repository as it is now archived due to not dprint not working correctly under pre-commit: https://github.com/adamchainz/pre-commit-dprint

Remove adamchainz/pre-commit-dprint

---

sections/advanced.md

Old actions which use node 12 currently spew a warning, see [1].
Let's use the latest version in the documentation here to help future users.
[1]: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

sections/advanced.md: Avoid warning on old action

---

all-repos.yaml

^-- `pre-commit` is in the name since this is a hook that modifies `pre-commit` config

Add `pre-commit/sync-pre-commit-deps`

---

sections/advanced.md

*post_commit* was missing from the list "Supported git hooks": https://pre-commit.com/#supported-git-hooks

post_commit missing from list "Supported git hooks"

---

sections/advanced.md

Added missing `m` in the word `comit`.

docs: fix typo

---

all-repos.yaml
make_all_hooks.py

this adds an additional check to the hooks page which requires names not cause wrapping by default
if you've been linked to this PR -- it's because your repository was disabled -- please pick a shorter `name` and re-enable your repository.  the limit for names to be included on `hooks.html` is 50 characters (anything more than this will stretch the default pre-commit output)

require short names by default

---

make_all_hooks.py

the particular one was https://github.com/antonbabenko/pre-commit-terraform/blob/03705ce283b735a4b8ae097e7486ea9257b4fd97/.pre-commit-hooks.yaml#L89

allow deprecated hooks to exceed character limit

---

all-repos.yaml

Add unimport & unexport

---

sections/new-hooks.md

Minor improvements to the docs on `golang` hooks:
- In `golang` hooks, `additional_dependencies` can be used. According to the existing docs on other language hooks, I have added a note on that. See also issue #797.
- The second paragraph is a summary of my findings from setting up `golang` hooks. It might be worth adding this for the benefit of others?

Extend golang docs: additional dependencies and tooling semantics

---

all-repos.yaml

Alternative to actionlint-py that makes use of `golang` directly. In contrast to when this was requested to be added in https://github.com/pre-commit/pre-commit.com/pull/702, the config contains now a `golang` entry.
The repo contains `language: system` and `language: system`, but since it contains `language: golang` as well, I ticked that box.

Add actionlint to list of pre-commit hooks

---

all-repos.yaml

Hi there,
I created a pre-commit hook which creates a .env.example file (derived from the .env file).
My new repository:

Added clean-dotenv to all-repos.yaml

---

all-repos.yaml

Addresses [#164](https://github.com/dbt-checkpoint/dbt-checkpoint/issues/164) in `dbt-checkpoint`. Previously `dbt-checkpoint` contained hooks with names > 50 characters, [#209](https://github.com/dbt-checkpoint/dbt-checkpoint/pull/209) fixed this.

Re-enabling dbt-checkpoint now that names are <=50 chars

---

sections/advanced.md
sections/cli.md
sections/new-hooks.md
sections/plugins.md

- remove `python_venv`
- remove 2.x references

update docs for pre-commit 4.0

---

sections/hooks.md

I think this fulfills the criteria:
- ✅  the tool must already be fairly popular (>500 stars):
- it has over 1100 stars, and >300k monthly downloads on PyPI stats
- ✅ the tool must use a managed language (no system / script / docker hooks):
- yup, it has `types_or: [jupyter, markdown]`
- ✅ the tool must operate on files
- yup

Add nbqa to list of hooks

---

sections/new-hooks.md

See pre-commit PR: https://github.com/pre-commit/pre-commit/pull/3348

Documentation for julia hooks

---

sections/hooks.md

The current Markdownlint hook is in Ruby.
Mention a popular Node-based one as well.

docs: add igorshubovych/markdownlint-cli to hooks page

---

sections/hooks.md

It was copy-pasted from previous link for shell, and currently point to wrong search result. This PR fix that.

docs: Fix missleading link

---

sections/hooks.md

Follow-up to #1017
My bad, I didn't remove `"` in the end when fixing link, which lead to search of `^\.pre-commit-hooks\.yaml"` file instead of `^\.pre-commit-hooks\.yaml`

docs: Fix broken link
