pre-commit/pre-commit.com

all-repos.yaml

@shihoonhootsuite thanks for the great article: http://code.hootsuite.com/using-yelps-pre-commit-hooks/

Add https://github.com/hootsuite/pre-commit-php

---

index.mako

add Alex Tsai to contributors

---

index.mako

excuse the branch name, autogen'd by github.

add Ara to contributors

---

.pre-commit-config.yaml
all-repos.yaml

Add SamWhited/go-pre-commit

---

index.mako

https://github.com/pre-commit/pre-commit/pull/258
Thanks!

Add meunierd to contributors

---

index.mako

Mention ggrep for osx

---

all-repos.yaml

See https://github.com/feross/standard.

Add mirror for standard

---

index.mako

This fixes https://github.com/pre-commit/pre-commit/issues/267

index: fix hook arguments

---

index.mako

Documentation update for confining hooks to be run at a certain stage.

Documentation for hook stages

---

index.mako

@asottile I'm happy to modify the wording as necessary.

Added the `additional_dependencies` attribute to docs

---

scss/main.scss

@mfnkl @theresama
Before:
After:

Fix responsive layout by allowing <code> to wrap

---

index.mako

Also added PR to homebrew to update to latest version https://github.com/Homebrew/homebrew/pull/49111

Added homebrew to install methods

---

index.mako

Document automatically merged files

---

all-repos.yaml

pre-commit hook which formats Terraform configuration files

Added antonbabenko/pre-commit-terraform

---

all-repos.yaml

From https://github.com/willthames/ansible-lint/pull/196
Thanks @jzafran @willthames!

Add willthames/ansible-lint to repositories list

---

.pre-commit-config.yaml
.travis.yml
Makefile
make_all_hooks.py
make_templates.py

- Upgrade to python3.5
- Clean up some py26isms and add some py35isms
- Upgrade virtualenv so manylinux wheels are used in travis-ci

Faster installation by upgrading virtualenv

---

all-repos.yaml

Signed-off-by: Artur Troian <troian.ap@gmail.com>

Add git@github.com:troian/pre-commit-golang.git

---

all-repos.yaml

Add clang-format hook for pre-commit

Add pre-commit-clang-format

---

Makefile
index.mako

I took the supported languages section and split it up into per-language sections

Add separate sections for each language

---

make_all_hooks.py

Update make_all_hooks.py for .pre-commit-hooks.yaml

---

all-repos.yaml

Hooks for validating and also formatting terraform code.

Add terraform hooks

---

index.mako

Based on a discussion in https://github.com/pre-commit/pre-commit/issues/591

Document long regular expressions

---

.gitignore
index.mako
requirements-dev.txt
template_lib.py

I for one keep making html mistakes!
This swaps bits of the html out for inline markdown, which imo is both easier to _write_ and _edit_.
I only did some parts of the file -- if this seems good I'll do more of the file and add a few features to the markdown parser such that I can eliminate even more html blocks.

Write more markdown, less html

---

index.mako

Document install-local does not function on windows

---

index.mako
template_lib.py

Document new configuration

---

all-repos.yaml

A Bash beautifier for the masses. https://pypi.python.org/pypi/beautysh

Add beautysh to the list of repos

---

index.mako

fixed minor typo in documentation

---

.pre-commit-config.yaml
index.mako

Resolves pre-commit/pre-commit#697

Document `py` launcher translation for windows

---

all-repos.yaml

Add xcodeproj-sort-pre-commit-hook

---

all-repos.yaml

PR here: https://github.com/jorisroovers/gitlint/pull/62
CC @jorisroovers

Add jorisroovers/gitlint to list of hooks

---

all-repos.yaml

Thanks again @ambv and @dcramer!

Add ambv/black

---

all-repos.yaml

Add two new hook repos. One to contain some Ansible check features and the other for Docker.
**Ansible**
Currently contains a check that vault files are encrypted before commit.
**Docker**
Contains a check to validate `docker-compose.y[a]ml` files are valid by using `docker-compose config`

Add new hooks for Ansible and Docker checks

---

index.mako

Fix typo under python_venv

---

all-repos.yaml

Add some repos I created for our local requirements that might be useful for others.

Add mattlqx repos

---

index.mako

noticed as part of https://github.com/pre-commit/pre-commit/issues/782  CC @ssbarnea

Move the "Developing hooks interactively" section higher

---

all-repos.yaml

Plugin to search and replace arbitrary strings in the commits. Handy for when you have a mirror of a repo you'd rather be using, or enforcing copyright dates or whatever!

add search-and-replace plugin

---

all-repos.yaml

Add Nim Hooks, written by @asottile 
:cat:

Add Nim Hooks, written by @asottile

---

all-repos.yaml

- https://github.com/PyCQA/bandit/pull/411

Add bandit to list of hook repos

---

all-repos.yaml

Add dockerfilelint hook for others that is based on https://github.com/replicatedhq/dockerfilelint

Add dockerfilelint

---

index.mako

Drop system level installation instructions

---

index.mako
requirements-dev.txt

lots of features in this cycle!

Updates for pre-commit 1.14

---

index.mako

Add "args" parameter to Creating new hooks section

---

package.json

(this probably doesn't affect us, but there was a banner on github and it was easy enough to upgrade)

sec: upgrade bootstrap-sass

---

all-repos.yaml

Adding in https://github.com/fortman/pre-commit-prometheus

Adding in prometheus validation repo

---

all-repos.yaml

Have plans to add quite a few hooks here, but figured I'd be proactive in getting myself added.

Add syntaqx/git-hooks

---

all-repos.yaml

Adds belminf/pre-commit-chef

---

all-repos.yaml

https://github.com/pocc/pre-commit-hooks

Add C linters as a supported repository

---

all-repos.yaml

Adding a hook for the Angular-cli's built-in lint command

Added Angular-cli ng lint hook to the list

---

all-repos.yaml

ambv/black => python/black

---

index.mako

Clarification following up https://github.com/jorisroovers/gitlint/issues/86#issuecomment-503321708

Clarify Confining hooks to run at certain stages

---

all-repos.yaml

(py)poetry and gitlab-ci checks

add poetry and gitlab-ci hooks

---

all-repos.yaml

Thanks @akbiggs / @myint!
https://github.com/myint/docformatter/pull/25

Add myint/docformatter to hooks list

---

all-repos.yaml

Adds R hooks from https://github.com/lorenzwalthert/pre-commit-hooks. Anything else I have to do?

add R hooks

---

all-repos.yaml

add FelixSeptem hook

---

all-repos.yaml

Add relint

---

index.mako

Expand docs for hook environments

---

index.mako

The package has been renamed on conda-forge:
https://github.com/conda-forge/pre_commit-feedstock/issues/35
https://github.com/conda-forge/pre-commit-feedstock

Update conda install command

---

all-repos.yaml

thg-consulting/inspectortiger#12

Add inspectortiger

---

all-repos.yaml

Adding hooks for Jupyter notebooks.

Add nbhooks to all-repos.yaml

---

all-repos.yaml

Adds new hook for vint, which was just merged to master
https://github.com/Kuniwak/vint/commit/9a239b20be279324ced3b34ed71f84a63edfd4fb

Add vint for vim script linting

---

all-repos.yaml

Add shellcheck-py

---

all-repos.yaml

As per title.
Please let me know if I need to update anything else.

Adding nbstripout to available hooks

---

all-repos.yaml

There are other hooks for this, but they didn't have args setup so I made my own. ¯\\_(ツ)_/¯

Add pre-commit-hooks-cpp

---

all-repos.yaml

adds https://github.com/Bahjat/pre-commit-golang

adds pre-commit-golang

---

index.mako

resolves pre-commit/pre-commit-hooks#432

Add note about overriding `types`

---

index.mako
scss/main.scss
template_lib.py

render the pre-commit version directly in output

---

all-repos.yaml

Greetings!
Just adding my hooks repo to the list:
* https://github.com/TekWizely/pre-commit-golang
Please let me know if you have any questions or need any other actions from me.
Thank you,
-TW

Adds TekWizely/pre-commit-golang to all-repos.yaml

---

base.mako

Closes #194, relates to https://github.com/pre-commit/pre-commit/pull/1334

Add pre-commit badge

---

all-repos.yaml

Quite a useful one we use org-wide

Add Yelp/detect-secrets

---

index.mako

Docs for https://github.com/pre-commit/pre-commit/pull/1303
"New in version" to be updated once known.

Add Perl hook docs

---

all-repos.yaml

Refs https://github.com/perltidy/perltidy/pull/20

Add perltidy/perltidy

---

all-repos.yaml

*Changes*:
- Adds twu/skjold to `all-hooks.yaml`
:bow:

Add twu/skjold to hooks list.

---

all-repos.yaml

Add `commitizen` to the list of supported hooks

---

index.mako

This adds docs for the new `post-checkout` hook.

Add docs for post-checkout

---

all-repos.yaml

Hooks for Java static code analysis.

Please add Java hooks repository

---

index.mako

Typo from https://github.com/pre-commit/pre-commit.github.io/pull/307

index: use backtics for post-checkout

---

all-repos.yaml

Some cross-platform options for Golang hooks.

Added github.com/lietu/go-pre-commit

---

all-repos.yaml

[shellcheck-py] Update URL

---

all-repos.yaml

This repo has a fairly basic `system` hook for ocamlformat

Add ocamlformat hook repo

---

all-repos.yaml

Reverts pre-commit/pre-commit.github.io#336
See https://github.com/pre-commit/pre-commit.github.io/pull/336#issuecomment-626357122

Revert "Add mathieu-lemay/pre-commit-rust"

---

all-repos.yaml

https://github.com/myint/rstcheck/pull/63

Add rstcheck

---

all-repos.yaml

Add a couple hooks

---

install-local.py

fixup install-local return value

---

all-repos.yaml

Adding a link to my dotnet-format hook

Add dotnet-format precommit hook

---

index.mako

Add an example for caching in Gitlab CI to the docs.

Add a caching example for Gitlab

---

all-repos.yaml

Adding my Markdown formatter to the hooks list

Add mdformat hook

---

all-repos.yaml

Changed the following two repos:
* https://gitlab.com/daverona/pre-commit-cpp to https://gitlab.com/daverona/pre-commit/cpp
* https://gitlab.com/daverona/pre-commit-php to https://gitlab.com/daverona/pre-commit/php
Thanks.

Change repo addresses

---

all-repos.yaml

Not sure if anything else is needed. If so, let me know :)

Add pre-commit hooks for Open Policy Agent (OPA)

---

all-repos.yaml

Adds pydantic-to-schema hook to supported hooks list

[PR] Adds pydantic-to-schema hook to supported hooks list

---

index.mako

background, see [SO](https://stackoverflow.com/questions/64036351/pre-commit-for-local-hook-gives-error-unrecognized-arguments-pre-commit-conf)

Explanation about local hooks

---

all-repos.yaml

See https://github.com/prettier/prettier/issues/9459 and https://github.com/prettier/prettier/pull/8937

Update prettier hook repo

---

all-repos.yaml

Hope this is alright, the hooks themselves seem to work on my machine :)

Add godot gdscript toolkit to hooks list

---

all-repos.yaml

The hook searches the current branch for something looking like a jira issue and prepends the commit message.
It is a prepare-commit-msg hook.

Add add-msg-issue-preffix-hook to supported (prepare-commit-msg)

---

all-repos.yaml

This PR adds the CleverCSV mirror repository

Add CleverCSV to list of repos

---

index.mako

A first pass at adding some simple coursier documentation.

first pass at coursier doc

---

all-repos.yaml

https://github.com/milin/gitown

Add gitown

---

all-repos.yaml

FYI, @Cretezy, @dluksza, @Matt-Gleich.

Add some Dart/Flutter related hooks to `all-repos.yaml`

---

all-repos.yaml

Hi,
this commits adds [md-toc](https://github.com/frnmst/md-toc) to the list.
Thanks

Add md-toc hook.

---

all-repos.yaml

Hello @asottile !
This PR adds [check-untracked-migrations](https://github.com/ecugol/pre-commit-hooks-django) hook.

Add check-untracked-migrations hook

---

all-repos.yaml

Now that I've finally worked up the courage to produce some publicly consumable hooks, why not another one?
This is just a regex replacement over text files, documented and packaged up.

Add sirosen/fix-smartquotes to all-repos

---

all-repos.yaml

Hi! 
I've just finished writing my first real pre-commit hook, and I thought I would add it to the list 🎉
Any feedback on the implementation would also be welcome if you have any 👏
Here's the repo: https://github.com/sondrelg/pep585-upgrade

Add sondrelg/pep585-upgrade to all hooks

---

all-repos.yaml

Register hooks from https://github.com/jendrikseipp/vulture

Register hook for vulture

---

all-repos.yaml

Hi,
Adding a hook for [no-string-hints](https://github.com/MarcoGorelli/no-string-hints)

Add no-string-hints

---

all-repos.yaml

ansible-lint has been moved to the ansible-community oragnisation

Move ansible-lint to ansible-community

---

all-repos.yaml

A little tool to automatically convert relative imports to absolute ones

abs-imports

---

all-repos.yaml

Added in https://github.com/dotnet/format/pull/872

Add dotnet-format to the list of hooks

---

all-repos.yaml

Rendered unnecessary by https://github.com/asottile/pyupgrade/pull/406

No no-string-hints

---

all-repos.yaml

Linter for bitbake (yocto) recipe files.

Add oelint-adv

---

all-repos.yaml

Add pre-commit hooks for android-kotlin
https://github.com/jggomez/pre-commit-android-kotlin

Add pre-commit hooks for android-kotlin

---

all-repos.yaml

Add [gitleaks](https://github.com/zricethezav/gitleaks).

Add Gitleaks

---

all-repos.yaml

Added https://github.com/hugoh/pre-commit-fish to the list of hooks.

Added pre-commit-fish

---

all-repos.yaml

The repository contains some hooks to find some LaTeX mistakes I kept running into.

Add pre-commit LaTeX hooks

---

all-repos.yaml

broken here: https://github.com/twu/skjold/pull/48/files#r655524560

Disable skjold

---

all-repos.yaml

tox-ini-fmt supports pre-commit

Add hook for tox-ini-fmt

---

all-repos.yaml

add pre-commit-gitlab-ci

---

all-repos.yaml

Add pre-commit hook to validate xml using xmllint.

Add `xmllint` check

---

all-repos.yaml

add mirrors-clang-format

---

all-repos.yaml

[A spell checker for code](https://github.com/streetsidesoftware/cspell).

Add cspell to all_repos.yaml

---

all-repos.yaml

https://github.com/realm/SwiftLint/pull/3714

Add SwiftLint

---

all-repos.yaml

https://github.com/adamchainz/pre-commit-oxipng

Add adamchainz/pre-commit-oxipng mirror

---

.gitattributes

Reverts pre-commit/pre-commit.com#581
cc @adamchainz

Revert "Set Git merge=union for all-repos.yaml"

---

all-repos.yaml

Signed-off-by: Liam Beguin <liambeguin@gmail.com>

Use upstream url for robotframework-tidy

---

all-repos.yaml

Doc'd here: https://standardjs.com/#use-a-pre-commit-hook
Improving hook description here: https://github.com/standard/standard/pull/1774

Add Standard JS

---

all-repos.yaml

Docs here: https://github.com/dannysepler/rm_unneeded_f_str

Add rm_unneeded_f_str

---

all-repos.yaml

Adding a hook I just finished implementing to lint and render .dot files
https://github.com/bagerard/graphviz-dot-hooks

add graphviz .dot linter/renderer hook

---

all-repos.yaml

Installable from https://pypi.org/project/ufmt/

Add µfmt hook

---

all-repos.yaml

https://github.com/daveshanley/vacuum

Add daveshanley/vacuum

---

all-repos.yaml

(Don't worry, I removed `fail_fast: true` 😜)
- [`README.md`](https://github.com/nuztalgia/botstrap#git-hooks)
- [`.pre-commit-hooks.yaml`](https://github.com/nuztalgia/botstrap/blob/main/.pre-commit-hooks.yaml)

Add nuztalgia/botstrap

---

sections/new-hooks.md

Thank you Anthony, for everything! See you soon on AOC ;)

Surround hook declaration file name with backticks

---

sections/advanced.md
sections/new-hooks.md

Per discussion at and around
https://github.com/pre-commit/pre-commit/issues/2076#issuecomment-933717382

Elaborate on hook level confinement, add a few examples

---

all-repos.yaml

check signature params for proper documentation

add docsig

---

all-repos.yaml

Add adamchainz/django-upgrade and move blacken-docs

---

all-repos.yaml

Update cfn-lint repo URL

---

all-repos.yaml

feat: Add vCard validator

---

all-repos.yaml

https://github.com/Data-Liberation-Front/csvlint.rb#via-pre-commit

csvlint support

---

all-repos.yaml

add dbt-checkpoint to list of repos

---

all-repos.yaml

add yamlfmt to all-repos

---

sections/plugins.md

Update example for default_stages

---

all-repos.yaml

add enforce-notebook-run-order

---

all-repos.yaml

Add `mxr/unkey`

---

all-repos.yaml

[actionlint-py](https://github.com/Mateusz-Grzelinski/actionlint-py/) is a pre-commit hook for [actionlint](https://github.com/rhysd/actionlint).

Add actionlint-py hook

---

all-repos.yaml

Add github-distributed-owners hook

---

all-repos.yaml

Add pydantic-hooks repo to all-repos.yaml file

---

all-repos.yaml

docs: add new pre-commit hook for conventional commits to all-repos.yaml

---

all-repos.yaml

Add numpydoc validation pre-commit hook

---

assets/copyable.js

fix copy script

---

all-repos.yaml

This hook for formatting GN build files https://gn.googlesource.com/gn/

Support gn-format hook in all-repos.yaml

---

all-repos.yaml

Add exif-stripper to all-repos.yaml

---

all-repos.yaml

referring to the maintained autopep8 repo instead of the archived mirror

---

all-repos.yaml

Add a repo with `.gitignore` tidyer
